CapabilityServiceTest via mqtt
DKE-Data/agrirouter-sdk-php pull request #26
Opened 2021-02-12 08:55 UTC by anschnit

CapabilityServiceTest via mqtt, Refactor PHP-Mqtt client builder and Monolog logger builder.

2021-02-15 07:41 UTC, saschadoemer requested changes

2021-02-16 10:43 UTC, saschadoemer reviewed
Test are failing locally.

![image](https://user-images.githubusercontent.com/1309344/108052300-34c3ba80-704c-11eb-89b6-76a07055596c.png)

2021-02-16 11:10 UTC, saschadoemer requested changes
Please see comments.

2021-02-16 13:33 UTC, anschnit commented on src/Api/Messaging/MqttClientInterface.php
>      interface MqttClientInterface
Opened: [https://github.com/DKE-Data/agrirouter-sdk-php/issues/29](url)

2021-03-07 13:23 UTC, merged